In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('train_features.csv')
df.head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,...,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,disbursement_method
0,43373,NaN,12000,12000,36 months,16.02%,422.01,C,C5,Driver,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash
1,24414,NaN,6300,6300,36 months,14.07%,215.54,C,C3,GMP Lead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash
2,46723,NaN,4500,4500,36 months,7.21%,139.38,A,A3,Accounts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash
3,24878,NaN,12000,12000,36 months,9.44%,384.06,B,B1,Client Processing Associate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash
4,39038,NaN,12000,12000,36 months,22.35%,460.47,D,D5,Construction Operator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash

In [3]:
df_labels = pd.read_csv('train_labels.csv')
df_labels.head()

      id  charged_off
0  43373            0
1  24414            0
2  46723            0
3  24878            0
4  39038            0

In [4]:
df.shape, df_labels.shape

((37745, 103), (37745, 2))

In [5]:
# pd.merge(df1, df2, on='Customer_id', how='inner')
df_merged = df.merge(df_labels, on='id', how='inner')
df_merged.head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,...,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,disbursement_method,charged_off
0,43373,NaN,12000,12000,36 months,16.02%,422.01,C,C5,Driver,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
1,24414,NaN,6300,6300,36 months,14.07%,215.54,C,C3,GMP Lead,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
2,46723,NaN,4500,4500,36 months,7.21%,139.38,A,A3,Accounts,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
3,24878,NaN,12000,12000,36 months,9.44%,384.06,B,B1,Client Processing Associate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
4,39038,NaN,12000,12000,36 months,22.35%,460.47,D,D5,Construction Operator,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0

In [6]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', -1)

In [7]:
len(df_merged.columns)

104

In [8]:
df_merged.isna().sum()

id                                     0
member_id                              37745
loan_amnt                              0
funded_amnt                            0
term                                   0
int_rate                               0
installment                            0
grade                                  0
sub_grade                              0
emp_title                              3565
emp_length                             3277
home_ownership                         0
annual_inc                             0
url                                    37745
desc                                   37745
purpose                                0
title                                  0
zip_code                               0
addr_state                             0
dti                                    92
delinq_2yrs                            0
earliest_cr_line                       0
inq_last_6mths                         0
mths_since_last_delinq                 20881
mths_since_last_record                 32170
open_acc                               0
pub_rec                                0
revol_bal                              0
revol_util                             53
total_acc                              0
initial_list_status                    0
collections_12_mths_ex_med             0
mths_since_last_major_derog            28640
application_type                       0
annual_inc_joint                       33007
dti_joint                              33007
acc_now_delinq                         0
tot_coll_amt                           0
tot_cur_bal                            0
open_acc_6m                            0
open_act_il                            0
open_il_12m                            0
open_il_24m                            0
mths_since_rcnt_il                     1234
total_bal_il                           0
il_util                                6255
open_rv_12m                            0
open_rv_24m                            0
max_bal_bc                             0
all_util                               13
total_rev_hi_lim                       0
inq_fi                                 0
total_cu_tl                            0
inq_last_12m                           0
acc_open_past_24mths                   0
avg_cur_bal                            3
bc_open_to_buy                         643
bc_util                                667
chargeoff_within_12_mths               0
delinq_amnt                            0
mo_sin_old_il_acct                     1234
mo_sin_old_rev_tl_op                   0
mo_sin_rcnt_rev_tl_op                  0
mo_sin_rcnt_tl                         0
mort_acc                               0
mths_since_recent_bc                   597
mths_since_recent_bc_dlq               29995
mths_since_recent_inq                  3146
mths_since_recent_revol_delinq         26574
num_accts_ever_120_pd                  0
num_actv_bc_tl                         0
num_actv_rev_tl                        0
num_bc_sats                            0
num_bc_tl                              0
num_il_tl                              0
num_op_rev_tl                          0
num_rev_accts                          0
num_rev_tl_bal_gt_0                    0
num_sats                               0
num_tl_120dpd_2m                       1010
num_tl_30dpd                           0
num_tl_90g_dpd_24m                     0
num_tl_op_past_12m                     0
pct_tl_nvr_dlq                         1
percent_bc_gt_75                       643
pub_rec_bankruptcies                   0
tax_liens                              0
tot_hi_cred_lim                        0
total_bal_ex_mort                      0
total_bc_limit                         0
total_il_high_credit_limit             0
revol_bal_joint                        33007
sec_app_earliest_cr_line               33007
sec_app_inq_last_6mths                 33007
sec_app_mort_acc                       33007
sec_app_open_acc                       33007
sec_app_revol_util                     33106
sec_app_open_act_il                    33007
sec_app_num_rev_accts                  33007
sec_app_chargeoff_within_12_mths       33007
sec_app_collections_12_mths_ex_med     33007
sec_app_mths_since_last_major_derog    36077
disbursement_method                    0
charged_off                            0
dtype: int64

In [9]:
data_dictionary = pd.read_excel('LCDataDictionary.xlsx')
data_dictionary

                                    LoanStatNew                                                                                                                                                                                                                                Description
0    acc_now_delinq                              The number of accounts on which the borrower is now delinquent.
1    acc_open_past_24mths                        Number of trades opened in past 24 months.
2    addr_state                                  The state provided by the borrower in the loan application
3    all_util                                    Balance to credit limit on all trades
4    annual_inc                                  The self-reported annual income provided by the borrower during registration.
5    annual_inc_joint                            The combined self-reported annual income provided by the co-borrowers during registration
6    application_type                            Indicates whether the loan is an individual application or a joint application with two co-borrowers
7    avg_cur_bal                                 Average current balance of all accounts
8    bc_open_to_buy                              Total open to buy on revolving bankcards.
9    bc_util                                     Ratio of total current balance to high credit/credit limit for all bankcard accounts.
10   chargeoff_within_12_mths                    Number of charge-offs within 12 months
11   collection_recovery_fee                     post charge off collection fee
12   collections_12_mths_ex_med                  Number of collections in 12 months excluding medical collections
13   delinq_2yrs                                 The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
14   delinq_amnt                                 The past-due amount owed for the accounts on which the borrower is now delinquent.
15   desc                                        Loan description provided by the borrower
16   dti                                         A ratio calculated using the borrowerâ€™s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrowerâ€™s self-reported monthly income.
17   dti_joint                                   A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported monthly income
18   earliest_cr_line                            The month the borrower's earliest reported credit line was opened
19   emp_length                                  Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
20   emp_title                                   The job title supplied by the Borrower when applying for the loan.*
21   fico_range_high                             The upper boundary range the borrowerâ€™s FICO at loan origination belongs to.
22   fico_range_low                              The lower boundary range the borrowerâ€™s FICO at loan origination belongs to.
23   funded_amnt                                 The total amount committed to that loan at that point in time.
24   funded_amnt_inv                             The total amount committed by investors for that loan at that point in time.
25   grade                                       LC assigned loan grade
26   home_ownership                              The home ownership status provided by the borrower during registrationÂ or obtained from the credit report.Â Our values are: RENT, OWN, MORTGAGE, OTHER
27   id                                          A unique LC assigned ID for the loan listing.
28   il_util                                     Ratio of total current balance to high credit/credit limit on all install acct
29   initial_list_status                         The initial listing status of the loan. Possible values are â€“ W, F
30   inq_fi                                      Number of personal finance inquiries
31   inq_last_12m                                Number of credit inquiries in past 12 months
32   inq_last_6mths                              The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
33   installment                                 The monthly payment owed by the borrower if the loan originates.
34   int_rate                                    Interest Rate on the loan
35   issue_d                                     The month which the loan was funded
36   last_credit_pull_d                          The most recent month LC pulled credit for this loan
37   last_fico_range_high                        The upper boundary range the borrowerâ€™s last FICO pulled belongs to.
38   last_fico_range_low                         The lower boundary range the borrowerâ€™s last FICO pulled belongs to.
39   last_pymnt_amnt                             Last total payment amount received
40   last_pymnt_d                                Last month payment was received
41   loan_amnt                                   The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.
42   loan_status                                 Current status of the loan
43   max_bal_bc                                  Maximum current balance owed on all revolving accounts
44   member_id                                   A unique LC assigned Id for the borrower member.
45   mo_sin_old_il_acct                          Months since oldest bank installment account opened
46   mo_sin_old_rev_tl_op                        Months since oldest revolving account opened
47   mo_sin_rcnt_rev_tl_op                       Months since most recent revolving account opened
48   mo_sin_rcnt_tl                              Months since most recent account opened
49   mort_acc                                    Number of mortgage accounts.
50   mths_since_last_delinq                      The number of months since the borrower's last delinquency.
51   mths_since_last_major_derog                 Months since most recent 90-day or worse rating
52   mths_since_last_record                      The number of months since the last public record.
53   mths_since_rcnt_il                          Months since most recent installment accounts opened
54   mths_since_recent_bc                        Months since most recent bankcard account opened.
55   mths_since_recent_bc_dlq                    Months since most recent bankcard delinquency
56   mths_since_recent_inq                       Months since most recent inquiry.
57   mths_since_recent_revol_delinq              Months since most recent revolving delinquency.
58   next_pymnt_d                                Next scheduled payment date
59   num_accts_ever_120_pd                       Number of accounts ever 120 or more days past due
60   num_actv_bc_tl                              Number of currently active bankcard accounts
61   num_actv_rev_tl                             Number of currently active revolving trades
62   num_bc_sats                                 Number of satisfactory bankcard accounts
63   num_bc_tl                                   Number of bankcard accounts
64   num_il_tl                                   Number of installment accounts
65   num_op_rev_tl                               Number of open revolving accounts
66   num_rev_accts                               Number of revolving accounts
67   num_rev_tl_bal_gt_0                         Number of revolving trades with balance >0
68   num_sats                                    Number of satisfactory accounts
69   num_tl_120dpd_2m                            Number of accounts currently 120 days past due (updated in past 2 months)
70   num_tl_30dpd                                Number of accounts currently 30 days past due (updated in past 2 months)
71   num_tl_90g_dpd_24m                          Number of accounts 90 or more days past due in last 24 months
72   num_tl_op_past_12m                          Number of accounts opened in past 12 months
73   open_acc                                    The number of open credit lines in the borrower's credit file.
74   open_acc_6m                                 Number of open trades in last 6 months
75   open_il_12m                                 Number of installment accounts opened in past 12 months
76   open_il_24m                                 Number of installment accounts opened in past 24 months
77   open_act_il                                 Number of currently active installment trades
78   open_rv_12m                                 Number of revolving trades opened in past 12 months
79   open_rv_24m                                 Number of revolving trades opened in past 24 months
80   out_prncp                                   Remaining outstanding principal for total amount funded
81   out_prncp_inv                               Remaining outstanding principal for portion of total amount funded by investors
82   pct_tl_nvr_dlq                              Percent of trades never delinquent
83   percent_bc_gt_75                            Percentage of all bankcard accounts > 75% of limit.
84   policy_code                                 publicly available policy_code=1\nnew products not publicly available policy_code=2
85   pub_rec                                     Number of derogatory public records
86   pub_rec_bankruptcies                        Number of public record bankruptcies
87   purpose                                     A category provided by the borrower for the loan request.
88   pymnt_plan                                  Indicates if a payment plan has been put in place for the loan
89   recoveries                                  post charge off gross recovery
90   revol_bal                                   Total credit revolving balance
91   revol_util                                  Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.
92   sub_grade                                   LC assigned loan subgrade
93   tax_liens                                   Number of tax liens
94   term                                        The number of payments on the loan. Values are in months and can be either 36 or 60.
95   title                                       The loan title provided by the borrower
96   tot_coll_amt                                Total collection amounts ever owed
97   tot_cur_bal                                 Total current balance of all accounts
98   tot_hi_cred_lim                             Total high credit/credit limit
99   total_acc                                   The total number of credit lines currently in the borrower's credit file
100  total_bal_ex_mort                           Total credit balance excluding mortgage
101  total_bal_il                                Total current balance of all installment accounts
102  total_bc_limit                              Total bankcard high credit/credit limit
103  total_cu_tl                                 Number of finance trades
104  total_il_high_credit_limit                  Total installment high credit/credit limit
105  total_pymnt                                 Payments received to date for total amount funded
106  total_pymnt_inv                             Payments received to date for portion of total amount funded by investors
107  total_rec_int                               Interest received to date
108  total_rec_late_fee                          Late fees received to date
109  total_rec_prncp                             Principal received to date
110  total_rev_hi_lim Â                           Total revolving high credit/credit limit
111  url                                         URL for the LC page with listing data.
112  verification_status                         Indicates if income was verified by LC, not verified, or if the income source was verified
113  verified_status_joint                       Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified
114  zip_code                                    The first 3 numbers of the zip code provided by the borrower in the loan application.
115  revol_bal_joint                              Sum of revolving credit balance of the co-borrowers, net of duplicate balances
116  sec_app_fico_range_low                       FICO range (high) for the secondary applicant
117  sec_app_fico_range_high                      FICO range (low) for the secondary applicant
118  sec_app_earliest_cr_line                     Earliest credit line at time of application for the secondary applicant
119  sec_app_inq_last_6mths                       Credit inquiries in the last 6 months at time of application for the secondary applicant
120  sec_app_mort_acc                             Number of mortgage accounts at time of application for the secondary applicant
121  sec_app_open_acc                             Number of open trades at time of application for the secondary applicant
122  sec_app_revol_util                           Ratio of total current balance to high credit/credit limit for all revolving accounts
123  sec_app_open_act_il                          Number of currently active installment trades at time of application for the secondary applicant
124  sec_app_num_rev_accts                        Number of revolving accounts at time of application for the secondary applicant
125  sec_app_chargeoff_within_12_mths             Number of charge-offs within last 12 months at time of application for the secondary applicant
126  sec_app_collections_12_mths_ex_med           Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant
127  sec_app_mths_since_last_major_derog          Months since most recent 90-day or worse rating at time of application for the secondary applicant
128  hardship_flag                               Flags whether or not the borrower is on a hardship plan
129  hardship_type                               Describes the hardship plan offering
130  hardship_reason                             Describes the reason the hardship plan was offered
131  hardship_status                             Describes if the hardship plan is active, pending, canceled, completed, or broken
132  deferral_term                               Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan
133  hardship_amount                             The interest payment that the borrower has committed to make each month while they are on a hardship plan
134  hardship_start_date                         The start date of the hardship plan period
135  hardship_end_date                           The end date of the hardship plan period
136  payment_plan_start_date                     The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is allowed to make interest-only payments.
137  hardship_length                             The number of months the borrower will make smaller payments than normally obligated due to a hardship plan
138  hardship_dpd                                Account days past due as of the hardship plan start date
139  hardship_loan_status                        Loan Status as of the hardship plan start date
140  orig_projected_additional_accrued_interest  The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hardship payment plan.
141  hardship_payoff_balance_amount              The payoff balance amount as of the hardship plan start date
142  hardship_last_payment_amount                The last payment amount as of the hardship plan start date
143  disbursement_method                         The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY
144  debt_settlement_flag                        Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company.
145  debt_settlement_flag_date                   The most recent date that the Debt_Settlement_Flag has been setÂ Â
146  settlement_status                           The status of the borrowerâ€™s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT
147  settlement_date                             The date that the borrower agrees to the settlement plan
148  settlement_amount                           The loan amount that the borrower has agreed to settle for
149  settlement_percentage                       The settlement amount as a percentage of the payoff balance amount on the loan
150  settlement_term                             The number of months that the borrower will be on the settlement plan
151  NaN                                         NaN
152  NaN                                         * Employer Title replaces Employer Name for all loans listed after 9/23/2013

In [10]:
df_merged.head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,disbursement_method,charged_off
0,43373,NaN,12000,12000,36 months,16.02%,422.01,C,C5,Driver,4 years,MORTGAGE,81000.0,NaN,NaN,debt_consolidation,Debt consolidation,280xx,NC,12.76,0,Dec-2005,1,48.0,NaN,7,0,4912,23.5%,15,w,0,48.0,Individual,NaN,NaN,0,0,174783,1,2,0,4,13.0,33668,82.0,2,5,2962,63.0,20900,1,1,2,9,24969.0,588.0,89.3,0,0,145.0,23,1,1,1,8.0,NaN,1.0,NaN,2,2,2,2,2,9,4,5,2,7,0.0,0,0,2,92.9,100.0,0,0,206618,38580,5500,40863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
1,24414,NaN,6300,6300,36 months,14.07%,215.54,C,C3,GMP Lead,4 years,RENT,39000.0,NaN,NaN,debt_consolidation,Debt consolidation,920xx,CA,21.42,0,Mar-2012,1,NaN,NaN,10,0,11876,59.4%,12,w,0,NaN,Individual,NaN,NaN,0,0,31046,0,1,0,2,14.0,19170,83.0,3,8,5153,72.0,20000,1,0,1,10,3105.0,6877.0,59.3,0,0,17.0,72,8,8,0,8.0,NaN,6.0,NaN,0,6,7,7,8,2,9,10,7,10,0.0,0,0,3,100.0,42.9,0,0,43140,31046,16900,23140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
2,46723,NaN,4500,4500,36 months,7.21%,139.38,A,A3,Accounts,3 years,RENT,78000.0,NaN,NaN,debt_consolidation,Debt consolidation,906xx,CA,2.17,0,May-2000,2,NaN,NaN,13,0,1715,5.2%,19,w,0,NaN,Individual,NaN,NaN,0,0,35329,0,8,1,2,10.0,33614,106.0,1,1,1196,54.0,33300,4,0,3,3,2718.0,21585.0,7.4,0,0,166.0,218,10,10,0,31.0,NaN,1.0,NaN,0,3,3,3,4,13,5,6,3,13,0.0,0,0,2,100.0,0.0,0,0,65092,35329,23300,31792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
3,24878,NaN,12000,12000,36 months,9.44%,384.06,B,B1,Client Processing Associate,10+ years,MORTGAGE,62000.0,NaN,NaN,debt_consolidation,Debt consolidation,441xx,OH,13.76,0,Feb-2003,0,NaN,NaN,22,0,9404,16.3%,33,w,0,NaN,Individual,NaN,NaN,0,0,75160,4,1,0,2,13.0,17123,67.0,6,9,6898,32.0,57600,3,1,2,12,3579.0,33602.0,17.0,0,0,162.0,179,1,1,1,1.0,NaN,5.0,NaN,0,1,3,9,13,7,20,25,3,22,0.0,0,0,7,100.0,0.0,0,0,133065,26527,40500,25465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0
4,39038,NaN,12000,12000,36 months,22.35%,460.47,D,D5,Construction Operator,10+ years,MORTGAGE,70000.0,NaN,NaN,debt_consolidation,Debt consolidation,751xx,TX,14.04,4,Nov-2001,2,13.0,NaN,18,0,17895,24.2%,45,w,0,13.0,Individual,NaN,NaN,0,7218,113702,9,2,2,4,6.0,16711,68.0,9,10,5373,35.0,73900,3,6,3,14,6317.0,32863.0,24.1,0,0,159.0,201,0,0,1,0.0,62.0,3.0,62.0,6,9,11,11,14,22,15,20,11,18,0.0,0,2,11,82.2,9.1,0,0,192842,34606,43300,24499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,0

In [11]:
df_merged['charged_off'].value_counts(normalize=True)

0    0.852855
1    0.147145
Name: charged_off, dtype: float64

In [12]:
df_merged.dtypes

id                                     int64
member_id                              float64
loan_amnt                              int64
funded_amnt                            int64
term                                   object
int_rate                               object
installment                            float64
grade                                  object
sub_grade                              object
emp_title                              object
emp_length                             object
home_ownership                         object
annual_inc                             float64
url                                    float64
desc                                   float64
purpose                                object
title                                  object
zip_code                               object
addr_state                             object
dti                                    float64
delinq_2yrs                            int64
earliest_cr_line                       object
inq_last_6mths                         int64
mths_since_last_delinq                 float64
mths_since_last_record                 float64
open_acc                               int64
pub_rec                                int64
revol_bal                              int64
revol_util                             object
total_acc                              int64
initial_list_status                    object
collections_12_mths_ex_med             int64
mths_since_last_major_derog            float64
application_type                       object
annual_inc_joint                       float64
dti_joint                              float64
acc_now_delinq                         int64
tot_coll_amt                           int64
tot_cur_bal                            int64
open_acc_6m                            int64
open_act_il                            int64
open_il_12m                            int64
open_il_24m                            int64
mths_since_rcnt_il                     float64
total_bal_il                           int64
il_util                                float64
open_rv_12m                            int64
open_rv_24m                            int64
max_bal_bc                             int64
all_util                               float64
total_rev_hi_lim                       int64
inq_fi                                 int64
total_cu_tl                            int64
inq_last_12m                           int64
acc_open_past_24mths                   int64
avg_cur_bal                            float64
bc_open_to_buy                         float64
bc_util                                float64
chargeoff_within_12_mths               int64
delinq_amnt                            int64
mo_sin_old_il_acct                     float64
mo_sin_old_rev_tl_op                   int64
mo_sin_rcnt_rev_tl_op                  int64
mo_sin_rcnt_tl                         int64
mort_acc                               int64
mths_since_recent_bc                   float64
mths_since_recent_bc_dlq               float64
mths_since_recent_inq                  float64
mths_since_recent_revol_delinq         float64
num_accts_ever_120_pd                  int64
num_actv_bc_tl                         int64
num_actv_rev_tl                        int64
num_bc_sats                            int64
num_bc_tl                              int64
num_il_tl                              int64
num_op_rev_tl                          int64
num_rev_accts                          int64
num_rev_tl_bal_gt_0                    int64
num_sats                               int64
num_tl_120dpd_2m                       float64
num_tl_30dpd                           int64
num_tl_90g_dpd_24m                     int64
num_tl_op_past_12m                     int64
pct_tl_nvr_dlq                         float64
percent_bc_gt_75                       float64
pub_rec_bankruptcies                   int64
tax_liens                              int64
tot_hi_cred_lim                        int64
total_bal_ex_mort                      int64
total_bc_limit                         int64
total_il_high_credit_limit             int64
revol_bal_joint                        float64
sec_app_earliest_cr_line               object
sec_app_inq_last_6mths                 float64
sec_app_mort_acc                       float64
sec_app_open_acc                       float64
sec_app_revol_util                     float64
sec_app_open_act_il                    float64
sec_app_num_rev_accts                  float64
sec_app_chargeoff_within_12_mths       float64
sec_app_collections_12_mths_ex_med     float64
sec_app_mths_since_last_major_derog    float64
disbursement_method                    object
charged_off                            int64
dtype: object

In [13]:
df_merged['term'].value_counts(normalize=True)

 36 months    0.728043
 60 months    0.271957
Name: term, dtype: float64

In [14]:
df_merged['int_rate'].value_counts(normalize=True)

 11.98%    0.020850
 10.90%    0.019605
  9.43%    0.019155
 12.61%    0.019102
 18.45%    0.018810
  9.92%    0.018360
 17.47%    0.018148
 15.04%    0.017671
  7.34%    0.017433
 14.07%    0.017300
 13.58%    0.016903
 21.85%    0.016453
 11.99%    0.016294
 19.42%    0.016135
  9.44%    0.016029
 20.39%    0.016002
  5.31%    0.015949
 15.05%    0.015578
 16.01%    0.015234
  6.71%    0.015075
  9.93%    0.014942
 14.08%    0.014783
 13.59%    0.014704
  7.35%    0.014651
 10.42%    0.014545
 10.41%    0.014492
  7.96%    0.014439
 12.62%    0.014413
  6.07%    0.013936
 16.02%    0.013220
  6.72%    0.013114
  7.97%    0.013061
 15.02%    0.012955
 13.56%    0.012902
 11.55%    0.012823
 10.91%    0.012531
  6.08%    0.011631
 16.14%    0.011445
 14.47%    0.011339
  7.84%    0.011313
 10.47%    0.011260
 16.91%    0.010889
  8.46%    0.010783
 17.09%    0.010597
 10.08%    0.010306
 12.73%    0.009882
 17.97%    0.009882
 11.05%    0.009829
 19.03%    0.009379
  7.21%    0.009299
  6.11%    0.009299
 21.45%    0.009273
 18.06%    0.009246
 18.94%    0.009087
 12.13%    0.009061
 13.06%    0.009008
 15.49%    0.008955
 11.06%    0.008902
  9.58%    0.008875
 14.03%    0.008849
 14.52%    0.008716
 20.00%    0.008690
 10.07%    0.008663
  7.46%    0.008345
  8.08%    0.008160
 26.77%    0.007948
  6.83%    0.007922
 20.89%    0.007816
 19.92%    0.007604
  5.32%    0.007524
 16.46%    0.007365
  6.67%    0.007127
 22.35%    0.006941
 10.56%    0.006888
  6.19%    0.006464
 28.72%    0.005749
 25.81%    0.005113
 24.84%    0.004954
 23.88%    0.003736
 23.40%    0.003683
 27.27%    0.003603
 22.90%    0.003524
 24.85%    0.003524
 23.87%    0.003126
 26.31%    0.002967
 26.30%    0.002888
 25.82%    0.002702
 24.37%    0.002623
 25.34%    0.002596
 11.80%    0.002464
  8.19%    0.002278
 10.72%    0.002093
 12.98%    0.002014
 30.79%    0.001908
 10.33%    0.001775
  8.81%    0.001696
 30.17%    0.001669
 22.91%    0.001616
 29.69%    0.001563
  7.56%    0.001378
 11.31%    0.001325
 30.75%    0.001245
 30.65%    0.001192
  6.46%    0.001166
  7.02%    0.001060
 30.84%    0.000212
 30.89%    0.000185
 30.94%    0.000106
  6.00%    0.000079
 30.99%    0.000026
Name: int_rate, dtype: float64

In [15]:
df_merged['emp_length'].value_counts()

10+ years    12707
2 years      3361
3 years      3066
< 1 year     2865
4 years      2435
1 year       2400
5 years      2319
6 years      1673
7 years      1440
8 years      1206
9 years      996
Name: emp_length, dtype: int64

In [16]:
df_num = df_merged.select_dtypes(include=['number']).copy()
df_num.head()

,id,member_id,loan_amnt,funded_amnt,installment,annual_inc,url,desc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,collections_12_mths_ex_med,mths_since_last_major_derog,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,charged_off
0,43373,NaN,12000,12000,422.01,81000.0,NaN,NaN,12.76,0,1,48.0,NaN,7,0,4912,15,0,48.0,NaN,NaN,0,0,174783,1,2,0,4,13.0,33668,82.0,2,5,2962,63.0,20900,1,1,2,9,24969.0,588.0,89.3,0,0,145.0,23,1,1,1,8.0,NaN,1.0,NaN,2,2,2,2,2,9,4,5,2,7,0.0,0,0,2,92.9,100.0,0,0,206618,38580,5500,40863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,24414,NaN,6300,6300,215.54,39000.0,NaN,NaN,21.42,0,1,NaN,NaN,10,0,11876,12,0,NaN,NaN,NaN,0,0,31046,0,1,0,2,14.0,19170,83.0,3,8,5153,72.0,20000,1,0,1,10,3105.0,6877.0,59.3,0,0,17.0,72,8,8,0,8.0,NaN,6.0,NaN,0,6,7,7,8,2,9,10,7,10,0.0,0,0,3,100.0,42.9,0,0,43140,31046,16900,23140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,46723,NaN,4500,4500,139.38,78000.0,NaN,NaN,2.17,0,2,NaN,NaN,13,0,1715,19,0,NaN,NaN,NaN,0,0,35329,0,8,1,2,10.0,33614,106.0,1,1,1196,54.0,33300,4,0,3,3,2718.0,21585.0,7.4,0,0,166.0,218,10,10,0,31.0,NaN,1.0,NaN,0,3,3,3,4,13,5,6,3,13,0.0,0,0,2,100.0,0.0,0,0,65092,35329,23300,31792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,24878,NaN,12000,12000,384.06,62000.0,NaN,NaN,13.76,0,0,NaN,NaN,22,0,9404,33,0,NaN,NaN,NaN,0,0,75160,4,1,0,2,13.0,17123,67.0,6,9,6898,32.0,57600,3,1,2,12,3579.0,33602.0,17.0,0,0,162.0,179,1,1,1,1.0,NaN,5.0,NaN,0,1,3,9,13,7,20,25,3,22,0.0,0,0,7,100.0,0.0,0,0,133065,26527,40500,25465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,39038,NaN,12000,12000,460.47,70000.0,NaN,NaN,14.04,4,2,13.0,NaN,18,0,17895,45,0,13.0,NaN,NaN,0,7218,113702,9,2,2,4,6.0,16711,68.0,9,10,5373,35.0,73900,3,6,3,14,6317.0,32863.0,24.1,0,0,159.0,201,0,0,1,0.0,62.0,3.0,62.0,6,9,11,11,14,22,15,20,11,18,0.0,0,2,11,82.2,9.1,0,0,192842,34606,43300,24499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [17]:
df_num.isna().sum()

id                                     0
member_id                              37745
loan_amnt                              0
funded_amnt                            0
installment                            0
annual_inc                             0
url                                    37745
desc                                   37745
dti                                    92
delinq_2yrs                            0
inq_last_6mths                         0
mths_since_last_delinq                 20881
mths_since_last_record                 32170
open_acc                               0
pub_rec                                0
revol_bal                              0
total_acc                              0
collections_12_mths_ex_med             0
mths_since_last_major_derog            28640
annual_inc_joint                       33007
dti_joint                              33007
acc_now_delinq                         0
tot_coll_amt                           0
tot_cur_bal                            0
open_acc_6m                            0
open_act_il                            0
open_il_12m                            0
open_il_24m                            0
mths_since_rcnt_il                     1234
total_bal_il                           0
il_util                                6255
open_rv_12m                            0
open_rv_24m                            0
max_bal_bc                             0
all_util                               13
total_rev_hi_lim                       0
inq_fi                                 0
total_cu_tl                            0
inq_last_12m                           0
acc_open_past_24mths                   0
avg_cur_bal                            3
bc_open_to_buy                         643
bc_util                                667
chargeoff_within_12_mths               0
delinq_amnt                            0
mo_sin_old_il_acct                     1234
mo_sin_old_rev_tl_op                   0
mo_sin_rcnt_rev_tl_op                  0
mo_sin_rcnt_tl                         0
mort_acc                               0
mths_since_recent_bc                   597
mths_since_recent_bc_dlq               29995
mths_since_recent_inq                  3146
mths_since_recent_revol_delinq         26574
num_accts_ever_120_pd                  0
num_actv_bc_tl                         0
num_actv_rev_tl                        0
num_bc_sats                            0
num_bc_tl                              0
num_il_tl                              0
num_op_rev_tl                          0
num_rev_accts                          0
num_rev_tl_bal_gt_0                    0
num_sats                               0
num_tl_120dpd_2m                       1010
num_tl_30dpd                           0
num_tl_90g_dpd_24m                     0
num_tl_op_past_12m                     0
pct_tl_nvr_dlq                         1
percent_bc_gt_75                       643
pub_rec_bankruptcies                   0
tax_liens                              0
tot_hi_cred_lim                        0
total_bal_ex_mort                      0
total_bc_limit                         0
total_il_high_credit_limit             0
revol_bal_joint                        33007
sec_app_inq_last_6mths                 33007
sec_app_mort_acc                       33007
sec_app_open_acc                       33007
sec_app_revol_util                     33106
sec_app_open_act_il                    33007
sec_app_num_rev_accts                  33007
sec_app_chargeoff_within_12_mths       33007
sec_app_collections_12_mths_ex_med     33007
sec_app_mths_since_last_major_derog    36077
charged_off                            0
dtype: int64

In [18]:
df_num = df_num.dropna(axis=1)
df_num.isna().sum()

id                            0
loan_amnt                     0
funded_amnt                   0
installment                   0
annual_inc                    0
delinq_2yrs                   0
inq_last_6mths                0
open_acc                      0
pub_rec                       0
revol_bal                     0
total_acc                     0
collections_12_mths_ex_med    0
acc_now_delinq                0
tot_coll_amt                  0
tot_cur_bal                   0
open_acc_6m                   0
open_act_il                   0
open_il_12m                   0
open_il_24m                   0
total_bal_il                  0
open_rv_12m                   0
open_rv_24m                   0
max_bal_bc                    0
total_rev_hi_lim              0
inq_fi                        0
total_cu_tl                   0
inq_last_12m                  0
acc_open_past_24mths          0
chargeoff_within_12_mths      0
delinq_amnt                   0
mo_sin_old_rev_tl_op          0
mo_sin_rcnt_rev_tl_op         0
mo_sin_rcnt_tl                0
mort_acc                      0
num_accts_ever_120_pd         0
num_actv_bc_tl                0
num_actv_rev_tl               0
num_bc_sats                   0
num_bc_tl                     0
num_il_tl                     0
num_op_rev_tl                 0
num_rev_accts                 0
num_rev_tl_bal_gt_0           0
num_sats                      0
num_tl_30dpd                  0
num_tl_90g_dpd_24m            0
num_tl_op_past_12m            0
pub_rec_bankruptcies          0
tax_liens                     0
tot_hi_cred_lim               0
total_bal_ex_mort             0
total_bc_limit                0
total_il_high_credit_limit    0
charged_off                   0
dtype: int64

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


X = df_num.drop('charged_off', axis=1)
y = df_num['charged_off']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

tree = DecisionTreeClassifier(criterion='gini',
                             max_depth=4, random_state=1)

tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)

print("Test score: {:.2f}".format(tree.score(X_test, y_test)))

Test score: 0.85