# Import

In [1]:
%matplotlib inline
import warnings
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.exceptions import DataConversionWarning
# from tqdm import tqdm
# data Process
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder
# model setup
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import f_classif, SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
# metric
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, accuracy_score, recall_score, roc_auc_score, confusion_matrix
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=RuntimeWarning)
warnings.filterwarnings(action='ignore', category=DeprecationWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 500)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [3]:
# df = pd.read_csv('/home/ec2-user/SageMaker/data/train_features.csv')
df = pd.read_csv('data/train_features.csv')
df2 = pd.read_csv('data/test_features.csv')
df3 = pd.read_csv('data/train_labels.csv')

## Useful functions

In [4]:
def submission(y_pred,X_test,outPath):
  id=pd.DataFrame(X_test.id,columns=['id']).astype('int32')
  prediction=pd.DataFrame(y_pred,columns=['charged_off'])
  final=pd.concat([id, prediction], axis=1).to_csv(outPath, index=False, 
                                                   header=['id','charged_off'])

# Preview Data

In [5]:
# preview data
print("df shape:"), print(df.shape), print("---"*20)
print("df2 shape:"), print(df2.shape), print("---"*20)
print("df3 shape:"), print(df3.shape), print("---"*20)

df shape:
(1309457, 103)
------------------------------------------------------------
df2 shape:
(26724, 103)
------------------------------------------------------------
df3 shape:
(1309457, 2)
------------------------------------------------------------

(None, None, None)

In [6]:
print("df columns:"), print(df.columns), print("---"*20)
print("df select_dtypes(include=[np.number]).columns.values:"), print(df.select_dtypes(include=[np.number]).columns.values), print("---"*20)
print("df select_dtypes(exclude=[np.number]).columns:"), print(df.select_dtypes(exclude=[np.number]).columns), print("---"*20)
print("df dtypes.sort_values(ascending=False):"), print(df.dtypes.sort_values(ascending=False)), print("---"*20)
print("df isnull().sum().sum():"), print(df.isnull().sum().sum()), print("---"*20)
print("df isna().sum().sort_values(ascending=False):"), print(df.isna().sum().sort_values(ascending=False)), print("---"*20)

df columns:
Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       ...
       'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'disbursement_method'], dtype='object', length=103)
------------------------------------------------------------
df select_dtypes(include=[np.number]).columns.values:
['id' 'member_id' 'loan_amnt' 'funded_amnt' 'installment' 'annual_inc'
 'url' 'dti' 'delinq_2yrs' 'inq_last_6mths' 'mths_since_last_delinq'
 'mths_since_last_record' 'open_acc' 'pub_rec' 'revol_bal' 'total_acc'
 'collections_12_mths_ex_med' 'mths_since_last_major_derog'
 'annual_inc_joint' 'dti_joint' 'acc_now_delinq' 'tot_coll_amt'
 'tot_cur_bal' 'open_acc_6m' 'open_act_il' 'open_il_12m' 'open_il_24m'
 'mths_since_rcnt_il' 'total_bal_il' 'il_util' 'open_rv_12m' 'open_rv_24m'
 'max_bal_bc' 'all_util' 'total_rev_hi_lim' 'inq_fi' 'total_cu_tl'
 'inq_last_12m' 'acc_open_past_24mths' 'avg_cur_bal' 'bc_open_to_buy'
 'bc_util' 'chargeoff_within_12_mths' 'delinq_amnt' 'mo_sin_old_il_acct'
 'mo_sin_old_rev_tl_op' 'mo_sin_rcnt_rev_tl_op' 'mo_sin_rcnt_tl'
 'mort_acc' 'mths_since_recent_bc' 'mths_since_recent_bc_dlq'
 'mths_since_recent_inq' 'mths_since_recent_revol_delinq'
 'num_accts_ever_120_pd' 'num_actv_bc_tl' 'num_actv_rev_tl' 'num_bc_sats'
 'num_bc_tl' 'num_il_tl' 'num_op_rev_tl' 'num_rev_accts'
 'num_rev_tl_bal_gt_0' 'num_sats' 'num_tl_120dpd_2m' 'num_tl_30dpd'
 'num_tl_90g_dpd_24m' 'num_tl_op_past_12m' 'pct_tl_nvr_dlq'
 'percent_bc_gt_75' 'pub_rec_bankruptcies' 'tax_liens' 'tot_hi_cred_lim'
 'total_bal_ex_mort' 'total_bc_limit' 'total_il_high_credit_limit'
 'revol_bal_joint' 'sec_app_inq_last_6mths' 'sec_app_mort_acc'
 'sec_app_open_acc' 'sec_app_revol_util' 'sec_app_open_act_il'
 'sec_app_num_rev_accts' 'sec_app_chargeoff_within_12_mths'
 'sec_app_collections_12_mths_ex_med'
 'sec_app_mths_since_last_major_derog']
------------------------------------------------------------
df select_dtypes(exclude=[np.number]).columns:
Index(['term', 'int_rate', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util', 'initial_list_status', 'application_type', 'sec_app_earliest_cr_line', 'disbursement_method'], dtype='object')
------------------------------------------------------------
df dtypes.sort_values(ascending=False):
disbursement_method                     object
emp_title                               object
initial_list_status                     object
revol_util                              object
earliest_cr_line                        object
addr_state                              object
zip_code                                object
title                                   object
desc                                    object
home_ownership                          object
emp_length                              object
purpose                                 object
sec_app_earliest_cr_line                object
int_rate                                object
sub_grade                               object
term                                    object
application_type                        object
grade                                   object
mths_since_last_major_derog            float64
tot_cur_bal                            float64
max_bal_bc                             float64
annual_inc_joint                       float64
open_rv_24m                            float64
dti_joint                              float64
acc_now_delinq                         float64
tot_coll_amt                           float64
open_acc_6m                            float64
il_util                                float64
open_act_il                            float64
total_bal_il                           float64
open_il_12m                            float64
open_il_24m                            float64
mths_since_rcnt_il                     float64
open_rv_12m                            float64
mths_since_last_record                 float64
collections_12_mths_ex_med             float64
dti                                    float64
member_id                              float64
loan_amnt                              float64
funded_amnt                            float64
installment                            float64
annual_inc                             float64
url                                    float64
delinq_2yrs                            float64
total_acc                              float64
inq_last_6mths                         float64
mths_since_last_delinq                 float64
total_rev_hi_lim                       float64
open_acc                               float64
pub_rec                                float64
revol_bal                              float64
all_util                               float64
inq_fi                                 float64
sec_app_mths_since_last_major_derog    float64
total_bal_ex_mort                      float64
num_sats                               float64
num_tl_120dpd_2m                       float64
num_tl_30dpd                           float64
num_tl_90g_dpd_24m                     float64
num_tl_op_past_12m                     float64
pct_tl_nvr_dlq                         float64
percent_bc_gt_75                       float64
pub_rec_bankruptcies                   float64
tax_liens                              float64
tot_hi_cred_lim                        float64
total_bc_limit                         float64
total_cu_tl                            float64
total_il_high_credit_limit             float64
revol_bal_joint                        float64
sec_app_inq_last_6mths                 float64
sec_app_mort_acc                       float64
sec_app_open_acc                       float64
sec_app_revol_util                     float64
sec_app_open_act_il                    float64
sec_app_num_rev_accts                  float64
sec_app_chargeoff_within_12_mths       float64
sec_app_collections_12_mths_ex_med     float64
num_rev_tl_bal_gt_0                    float64
num_rev_accts                          float64
num_op_rev_tl                          float64
num_il_tl                              float64
inq_last_12m                           float64
acc_open_past_24mths                   float64
avg_cur_bal                            float64
bc_open_to_buy                         float64
bc_util                                float64
chargeoff_within_12_mths               float64
delinq_amnt                            float64
mo_sin_old_il_acct                     float64
mo_sin_old_rev_tl_op                   float64
mo_sin_rcnt_rev_tl_op                  float64
mo_sin_rcnt_tl                         float64
mort_acc                               float64
mths_since_recent_bc                   float64
mths_since_recent_bc_dlq               float64
mths_since_recent_inq                  float64
mths_since_recent_revol_delinq         float64
num_accts_ever_120_pd                  float64
num_actv_bc_tl                         float64
num_actv_rev_tl                        float64
num_bc_sats                            float64
num_bc_tl                              float64
id                                       int64
dtype: object
------------------------------------------------------------
df isnull().sum().sum():
38843199
------------------------------------------------------------
df isna().sum().sort_values(ascending=False):
url                                    1309457
member_id                              1309457
sec_app_mths_since_last_major_derog    1303349
sec_app_revol_util                     1292681
revol_bal_joint                        1292373
sec_app_earliest_cr_line               1292372
sec_app_inq_last_6mths                 1292372
sec_app_mort_acc                       1292372
sec_app_open_acc                       1292372
sec_app_open_act_il                    1292372
sec_app_num_rev_accts                  1292372
sec_app_chargeoff_within_12_mths       1292372
sec_app_collections_12_mths_ex_med     1292372
dti_joint                              1285357
annual_inc_joint                       1285354
desc                                   1188346
mths_since_last_record                 1086702
mths_since_recent_bc_dlq                998737
mths_since_last_major_derog             965114
mths_since_recent_revol_delinq          871206
il_util                                 861176
mths_since_rcnt_il                      805160
all_util                                791575
total_cu_tl                             791525
inq_last_12m                            791525
open_acc_6m                             791525
open_il_12m                             791524
open_il_24m                             791524
total_bal_il                            791524
open_rv_12m                             791524
open_rv_24m                             791524
max_bal_bc                              791524
open_act_il                             791524
inq_fi                                  791524
mths_since_last_delinq                  660359
mths_since_recent_inq                   169844
num_tl_120dpd_2m                        114845
mo_sin_old_il_acct                      103229
emp_title                                83135
emp_length                               76101
pct_tl_nvr_dlq                           66389
avg_cur_bal                              66259
mo_sin_rcnt_rev_tl_op                    66239
mo_sin_old_rev_tl_op                     66239
num_rev_accts                            66239
num_tl_op_past_12m                       66238
total_rev_hi_lim                         66238
num_tl_90g_dpd_24m                       66238
num_tl_30dpd                             66238
tot_coll_amt                             66238
num_rev_tl_bal_gt_0                      66238
num_accts_ever_120_pd                    66238
num_op_rev_tl                            66238
num_il_tl                                66238
num_bc_tl                                66238
tot_cur_bal                              66238
total_il_high_credit_limit               66238
num_actv_rev_tl                          66238
mo_sin_rcnt_tl                           66238
num_actv_bc_tl                           66238
tot_hi_cred_lim                          66238
bc_util                                  60553
percent_bc_gt_75                         60213
bc_open_to_buy                           59808
mths_since_recent_bc                     58906
num_sats                                 54748
num_bc_sats                              54748
acc_open_past_24mths                     46359
total_bal_ex_mort                        46359
total_bc_limit                           46359
mort_acc                                 46359
title                                    16331
revol_util                                 829
pub_rec_bankruptcies                       682
dti                                        327
chargeoff_within_12_mths                    53
collections_12_mths_ex_med                  53
tax_liens                                   37
inq_last_6mths                               1
zip_code                                     1
sub_grade                                    0
installment                                  0
int_rate                                     0
term                                         0
funded_amnt                                  0
home_ownership                               0
loan_amnt                                    0
annual_inc                                   0
grade                                        0
disbursement_method                          0
purpose                                      0
addr_state                                   0
delinq_2yrs                                  0
earliest_cr_line                             0
open_acc                                     0
pub_rec                                      0
revol_bal                                    0
total_acc                                    0
initial_list_status                          0
application_type                             0
acc_now_delinq                               0
delinq_amnt                                  0
id                                           0
dtype: int64
------------------------------------------------------------

(None, None, None)

In [2]:
# list with more than 660359 NaN
list1 = ["url", "member_id", "sec_app_mths_since_last_major_derog", "sec_app_revol_util", "revol_bal_joint", 
         "sec_app_earliest_cr_line", "sec_app_inq_last_6mths", "sec_app_mort_acc", "sec_app_open_acc", 
         "sec_app_open_act_il", "sec_app_num_rev_accts", "sec_app_chargeoff_within_12_mths", 
         "sec_app_collections_12_mths_ex_med", "dti_joint", "annual_inc_joint", "desc", "mths_since_last_record", 
         "mths_since_recent_bc_dlq", "mths_since_last_major_derog", "mths_since_recent_revol_delinq", "il_util", 
         "mths_since_rcnt_il", "all_util", "total_cu_tl", "inq_last_12m", "open_acc_6m", "open_il_12m", 
         "open_il_24m", "total_bal_il", "open_rv_12m", "open_rv_24m", "max_bal_bc", "open_act_il", "inq_fi", 
         "mths_since_last_delinq"]

# df = df.drop(columns=list1)
# df2 = df2.drop(columns=list1)

In [8]:
df.head().T

                                                 0                        1               2                         3                          4
id                                         1246716                  1678744         1149018                   1349740                    1234365
loan_amnt                                    22000                    10000            7000                      1400                      19200
funded_amnt                                  22000                    10000            7000                      1400                      19200
term                                     36 months                36 months       36 months                 36 months                  36 months
int_rate                                     5.32%                    5.32%           6.97%                    13.67%                      8.18%
installment                                 662.53                   301.15          216.05                     47.63                     603.26
grade                                            A                        A               A                         C                          B
sub_grade                                       A1                       A1              A3                        C4                         B1
emp_title                   Transition Coordinator  Director HQ Controlling             NaN  Administrative Assistant  Plant Electrical Engineer
emp_length                               10+ years                  4 years             NaN                   5 years                   < 1 year
home_ownership                            MORTGAGE                 MORTGAGE            RENT                      RENT                       RENT
annual_inc                                  126000                   120000           80000                     49000                     150000
purpose                           home_improvement       debt_consolidation  major_purchase                   medical                credit_card
title                             Home improvement       Debt consolidation  Major purchase          Medical expenses    Credit card refinancing
zip_code                                     604xx                    019xx           653xx                     770xx                      971xx
addr_state                                      IL                       MA              MO                        TX                         OR
dti                                          28.99                    10.69           29.39                     25.07                      16.18
delinq_2yrs                                      0                        1               0                         0                          0
earliest_cr_line                          Oct-2000                 Jan-2002        Jan-2002                  Aug-2004                   Oct-1997
inq_last_6mths                                   0                        0               2                         0                          3
open_acc                                        12                       13              13                        12                          8
pub_rec                                          0                        0               0                         0                          1
revol_bal                                     9371                     9145            3703                     19979                      27000
revol_util                                     51%                      35%           10.4%                     79.6%                        56%
total_acc                                       18                       46              20                        18                         17
initial_list_status                              w                        w               f                         w                          f
collections_12_mths_ex_med                       0                        0               0                         0                          0
application_type                        Individual               Individual      Individual                Individual                 Individual
acc_now_delinq                                   0                        0               0                         0                          0
tot_coll_amt                                     0                        0               0                         0                      13774
tot_cur_bal                                 367985                    40945           78269                     38644                      64780
total_rev_hi_lim                             18351                    26100           35500                     25100                      48150
acc_open_past_24mths                             2                        4               6                         3                          4
avg_cur_bal                                  30665                     3150            6021                      3220                       8097
bc_open_to_buy                                3250                    16355           17930                      1411                       9630
bc_util                                         69                     35.9             6.1                      93.2                         56
chargeoff_within_12_mths                         0                        0               0                         0                          0
delinq_amnt                                      0                        0               0                         0                          0
mo_sin_old_il_acct                             145                      168             170                       111                        140
mo_sin_old_rev_tl_op                           182                      116              44                       136                        209
mo_sin_rcnt_rev_tl_op                            5                       31               4                        16                          6
mo_sin_rcnt_tl                                   2                       13               4                         5                          6
mort_acc                                         2                        0               0                         0                          0
mths_since_recent_bc                            57                       31               4                        16                          6
mths_since_recent_inq                           18                       20               1                        16                          6
num_accts_ever_120_pd                            2                        0               0                         0                          0
num_actv_bc_tl                                   3                        2               3                         7                          5
num_actv_rev_tl                                  7                        2               6                         8                          5
num_bc_sats                                      4                        3               4                         7                         11
num_bc_tl                                        4                        4               5                         8                         11
num_il_tl                                        7                       41              10                         2                          5
num_op_rev_tl                                    7                        4               8                        11                          5
num_rev_accts                                    9                        5              10                        16                         11
num_rev_tl_bal_gt_0                              7                        2               6                         8                          4
num_sats                                        12                       13              13                        12                          8
num_tl_120dpd_2m                               NaN                        0               0                         0                        NaN
num_tl_30dpd                                     0                        0               0                         0                          0
num_tl_90g_dpd_24m                               0                        0               0                         0                          0
num_tl_op_past_12m                               2                        0               4                         1                          1
pct_tl_nvr_dlq                                  89                     97.8             100                      94.4                        100
percent_bc_gt_75                                 0                        0               0                       100                         40
pub_rec_bankruptcies                             0                        0               0                         0                          0
tax_liens                                        0                        0               0                         0                          1
tot_hi_cred_lim                             451899                    74267          131514                     44615                     105204
total_bal_ex_mort                           198749                    40945           78269                     38644                      64780
total_bc_limit                                9750                    25500           19100                     20800                      48150
total_il_high_credit_limit                  210298                    48167           96014                     19515                      56850
disbursement_method                           Cash                     Cash            Cash                      Cash                       Cash

In [9]:
df2.head().T

                                             0                   1                   2                   3                      4
id                                     2264704             1896343             2077525             1846827                1210251
loan_amnt                                20000                4000               10000               12000                   2400
funded_amnt                              20000                4000               10000               12000                   2400
term                                 36 months           36 months           36 months           60 months              36 months
int_rate                                 8.18%              13.99%              10.99%              14.31%                  6.72%
installment                             628.39               136.7              327.34              281.16                   73.8
grade                                        B                   C                   B                   C                      A
sub_grade                                   B1                  C1                  B2                  C4                     A3
emp_title                      Superintendent            Seats Inc    Registered Nurse     Personal Banker  Respiratory Therapist
emp_length                             2 years             5 years             6 years             2 years                5 years
home_ownership                        MORTGAGE                RENT            MORTGAGE                RENT                    OWN
annual_inc                               64000               32000               89000               35360                60042.6
purpose                     debt_consolidation  debt_consolidation  debt_consolidation  debt_consolidation                  other
title                       Debt consolidation       Bills be gone  Debt consolidation  Debt consolidation                  Other
zip_code                                 320xx               539xx               770xx               805xx                  473xx
addr_state                                  FL                  WI                  TX                  CO                     IN
dti                                      12.45                16.2               18.04               30.96                    4.2
delinq_2yrs                                  0                   0                   2                   0                      0
earliest_cr_line                      Dec-2002            Sep-2006            Nov-2005            May-2003               Apr-2000
inq_last_6mths                               0                   0                   0                   0                      0
open_acc                                     9                   8                  12                   7                     14
pub_rec                                      0                   0                   0                   0                      0
revol_bal                                22607                5240               10675                6444                   4355
revol_util                               82.2%               77.1%               87.6%               37.9%                   7.6%
total_acc                                   12                  12                  21                  16                     31
initial_list_status                          f                   f                   w                   w                      w
collections_12_mths_ex_med                   0                   0                   0                   0                      0
application_type                    Individual          Individual          Individual          Individual             Individual
acc_now_delinq                               0                   0                   0                   0                      0
tot_coll_amt                                50                 NaN                   0                   0                      0
tot_cur_bal                              36978                 NaN               42555               86687                   5998
total_rev_hi_lim                         27500                 NaN               12500               17000                  57000
acc_open_past_24mths                         0                   3                   3                   2                      2
avg_cur_bal                               4109                 NaN                3869               12384                    600
bc_open_to_buy                            2893                1352                 418                2093                  44061
bc_util                                   88.7                79.2                90.5                73.8                    4.4
chargeoff_within_12_mths                     0                   0                   0                   0                      0
delinq_amnt                                  0                   0                   0                   0                      0
mo_sin_old_il_acct                          50                 NaN                 100                 126                    121
mo_sin_old_rev_tl_op                       147                 NaN                  95                 140                    213
mo_sin_rcnt_rev_tl_op                       56                 NaN                   8                   9                      9
mo_sin_rcnt_tl                              31                 NaN                   8                   9                      8
mort_acc                                     1                   0                   0                   3                      0
mths_since_recent_bc                        88                   7                  40                   9                     41
mths_since_recent_inq                      NaN                   7                 NaN                 NaN                      8
num_accts_ever_120_pd                        0                 NaN                   1                   0                      0
num_actv_bc_tl                               3                 NaN                   3                   3                      3
num_actv_rev_tl                              3                 NaN                   8                   4                      4
num_bc_sats                                  4                 NaN                   3                   4                      5
num_bc_tl                                    6                 NaN                   3                   6                      8
num_il_tl                                    4                 NaN                   9                   3                     13
num_op_rev_tl                                5                 NaN                   9                   6                     13
num_rev_accts                                7                 NaN                  11                  10                     18
num_rev_tl_bal_gt_0                          3                 NaN                   8                   4                      4
num_sats                                     9                 NaN                  12                   7                     14
num_tl_120dpd_2m                             0                 NaN                   0                   0                      0
num_tl_30dpd                                 0                 NaN                   0                   0                      0
num_tl_90g_dpd_24m                           0                 NaN                   2                   0                      0
num_tl_op_past_12m                           0                 NaN                   1                   2                      2
pct_tl_nvr_dlq                            91.7                 NaN                 100                93.7                    100
percent_bc_gt_75                            75                  50                66.7                  75                      0
pub_rec_bankruptcies                         0                   0                   0                   0                      0
tax_liens                                    0                   0                   0                   0                      0
tot_hi_cred_lim                          44000                 NaN               58690              117300                  59000
total_bal_ex_mort                        36978               15701               42555               86687                   5998
total_bc_limit                           25500                6500                1400                8000                  46100
total_il_high_credit_limit               16500                 NaN               46190              100300                   2000
disbursement_method                       Cash                Cash                Cash                Cash                   Cash

In [10]:
df3.head().T

                   0        1        2        3        4
id           1246716  1678744  1149018  1349740  1234365
charged_off        0        0        1        0        0

In [11]:
df = df.select_dtypes(include=[np.number])
df.columns

Index(['id', 'loan_amnt', 'funded_amnt', 'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'collections_12_mths_ex_med', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'],
      dtype='object')

In [12]:
for i in df.columns:
    df[i] = df[i].fillna(df[i].mean())
df.isna().sum().sort_values(ascending=False)

total_il_high_credit_limit    0
total_bc_limit                0
mo_sin_old_il_acct            0
delinq_amnt                   0
chargeoff_within_12_mths      0
bc_util                       0
bc_open_to_buy                0
avg_cur_bal                   0
acc_open_past_24mths          0
total_rev_hi_lim              0
tot_cur_bal                   0
tot_coll_amt                  0
acc_now_delinq                0
collections_12_mths_ex_med    0
total_acc                     0
revol_bal                     0
pub_rec                       0
open_acc                      0
inq_last_6mths                0
delinq_2yrs                   0
dti                           0
annual_inc                    0
installment                   0
funded_amnt                   0
loan_amnt                     0
mo_sin_old_rev_tl_op          0
mo_sin_rcnt_rev_tl_op         0
mo_sin_rcnt_tl                0
num_sats                      0
total_bal_ex_mort             0
tot_hi_cred_lim               0
tax_liens                     0
pub_rec_bankruptcies          0
percent_bc_gt_75              0
pct_tl_nvr_dlq                0
num_tl_op_past_12m            0
num_tl_90g_dpd_24m            0
num_tl_30dpd                  0
num_tl_120dpd_2m              0
num_rev_tl_bal_gt_0           0
mort_acc                      0
num_rev_accts                 0
num_op_rev_tl                 0
num_il_tl                     0
num_bc_tl                     0
num_bc_sats                   0
num_actv_rev_tl               0
num_actv_bc_tl                0
num_accts_ever_120_pd         0
mths_since_recent_inq         0
mths_since_recent_bc          0
id                            0
dtype: int64

# Baseline Model Prediction

In [16]:
################################ 
submission_url = 'Model1-prediction-baseline0.csv'

# 0 Data Source
train_features = pd.read_csv('data/train_features.csv')
train_labels = pd.read_csv('data/train_labels.csv')
test_features = pd.read_csv('data/test_features.csv')
# sample_submission = pd.read_csv('sample_submission.csv')

# 1 Set X & y - train & test
y_train = train_labels['charged_off']
X_train = train_features
X_test  = test_features

# 2 Data Wrangle
X_train = X_train.drop(columns=list1)
X_test = X_test.drop(columns=list1)
X_train = X_train[list(X_train.select_dtypes(include=[np.number]))]
X_test = X_test[list(X_train.select_dtypes(include=[np.number]))]
for i in X_train.columns:
    X_train[i] = X_train[i].fillna(X_train[i].mean())
for i in X_test.columns:
    X_test[i] = X_test[i].fillna(X_test[i].mean())
print("X_train.shape:",X_train.shape)
print("X_test.shape:",X_test.shape)

# 3 Set X & y - train & validation from X & y train
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

# 4 Make pipeline
pipeline = make_pipeline(
    RobustScaler(),
    SelectKBest(f_classif),
    LogisticRegression(random_state=0, solver='lbfgs')
)

param_grid = {
#     'selectkbest__k': range(4, len(X_train.columns)+1),
    'selectkbest__k': range(4, len(X_train.columns)+1),    
    }

# 5 Fit on the train set
gs = GridSearchCV(pipeline, param_grid=param_grid, cv=2, 
                  scoring='roc_auc', 
                  iid=False,
                  verbose=2)

gs.fit(X_train, y_train)

# 6 Validation Results
validation_score = gs.best_score_
print('Validation Score: ', validation_score)
print('Best parameter:', gs.best_params_)
print('Best estimator:', gs.best_estimator_)

# 7 Print which features was selected
selector = gs.best_estimator_.named_steps['selectkbest']
all_names = X_train.columns
selected_mask = selector.get_support()
selected_names=all_names[selected_mask]
unselected_names = all_names[~selected_mask]
print("-"*100)

print(all_names)
print("-"*100)
print('Features selected:')
for name in selected_names:
  print(name)
print("-"*100)

print("Features not selected:")
for name in unselected_names:
  print(name)
print("-"*100)

# 8 Make Prediction and Save submission
y_pred=gs.predict(X_test)
# for google colab
# submission_url = '/content/drive/My Drive/Colab Notebooks/Model1-prediction.csv'
submission(y_pred,test_features,submission_url)

print("train_labels.shape:",train_labels.shape)
print("submission csv shape:")
pd.read_csv(submission_url).shape

X_train.shape: (1309457, 52)
X_test.shape: (26724, 52)
(982092, 52) (327365, 52) (982092,) (327365,)
Fitting 2 folds for each of 49 candidates, totalling 98 fits
[CV] selectkbest__k=4 ................................................
[CV] ................................. selectkbest__k=4, total=   6.1s
[CV] selectkbest__k=4 ................................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.7s remaining:    0.0s

[CV] ................................. selectkbest__k=4, total=   4.4s
[CV] selectkbest__k=5 ................................................
[CV] ................................. selectkbest__k=5, total=   4.2s
[CV] selectkbest__k=5 ................................................
[CV] ................................. selectkbest__k=5, total=   4.2s
[CV] selectkbest__k=6 ................................................
[CV] ................................. selectkbest__k=6, total=   4.4s
[CV] selectkbest__k=6 ................................................
[CV] ................................. selectkbest__k=6, total=   4.5s
[CV] selectkbest__k=7 ................................................
[CV] ................................. selectkbest__k=7, total=   4.5s
[CV] selectkbest__k=7 ................................................
[CV] ................................. selectkbest__k=7, total=   4.5s
[CV] selectkbest__k=8 ................................................
[CV] ................................. selectkbest__k=8, total=   4.6s
[CV] selectkbest__k=8 ................................................
[CV] ................................. selectkbest__k=8, total=   4.6s
[CV] selectkbest__k=9 ................................................
[CV] ................................. selectkbest__k=9, total=   5.4s
[CV] selectkbest__k=9 ................................................
[CV] ................................. selectkbest__k=9, total=   4.7s
[CV] selectkbest__k=10 ...............................................
[CV] ................................ selectkbest__k=10, total=   5.5s
[CV] selectkbest__k=10 ...............................................
[CV] ................................ selectkbest__k=10, total=   5.4s
[CV] selectkbest__k=11 ...............................................
[CV] ................................ selectkbest__k=11, total=   6.4s
[CV] selectkbest__k=11 ...............................................
[CV] ................................ selectkbest__k=11, total=   5.9s
[CV] selectkbest__k=12 ...............................................
[CV] ................................ selectkbest__k=12, total=   6.1s
[CV] selectkbest__k=12 ...............................................
[CV] ................................ selectkbest__k=12, total=   6.3s
[CV] selectkbest__k=13 ...............................................
[CV] ................................ selectkbest__k=13, total=   6.8s
[CV] selectkbest__k=13 ...............................................
[CV] ................................ selectkbest__k=13, total=   6.8s
[CV] selectkbest__k=14 ...............................................
[CV] ................................ selectkbest__k=14, total=   6.7s
[CV] selectkbest__k=14 ...............................................
[CV] ................................ selectkbest__k=14, total=   7.4s
[CV] selectkbest__k=15 ...............................................
[CV] ................................ selectkbest__k=15, total=   7.2s
[CV] selectkbest__k=15 ...............................................
[CV] ................................ selectkbest__k=15, total=   7.2s
[CV] selectkbest__k=16 ...............................................
[CV] ................................ selectkbest__k=16, total=  10.5s
[CV] selectkbest__k=16 ...............................................
[CV] ................................ selectkbest__k=16, total=  10.0s
[CV] selectkbest__k=17 ...............................................
[CV] ................................ selectkbest__k=17, total=  12.0s
[CV] selectkbest__k=17 ...............................................
[CV] ................................ selectkbest__k=17, total=  11.7s
[CV] selectkbest__k=18 ...............................................
[CV] ................................ selectkbest__k=18, total=  12.6s
[CV] selectkbest__k=18 ...............................................
[CV] ................................ selectkbest__k=18, total=  12.5s
[CV] selectkbest__k=19 ...............................................
[CV] ................................ selectkbest__k=19, total=   8.1s
[CV] selectkbest__k=19 ...............................................
[CV] ................................ selectkbest__k=19, total=  11.9s
[CV] selectkbest__k=20 ...............................................
[CV] ................................ selectkbest__k=20, total=  12.5s
[CV] selectkbest__k=20 ...............................................
[CV] ................................ selectkbest__k=20, total=  11.3s
[CV] selectkbest__k=21 ...............................................
[CV] ................................ selectkbest__k=21, total=  12.1s
[CV] selectkbest__k=21 ...............................................
[CV] ................................ selectkbest__k=21, total=  13.3s
[CV] selectkbest__k=22 ...............................................
[CV] ................................ selectkbest__k=22, total=  12.2s
[CV] selectkbest__k=22 ...............................................
[CV] ................................ selectkbest__k=22, total=  13.4s
[CV] selectkbest__k=23 ...............................................
[CV] ................................ selectkbest__k=23, total=  13.6s
[CV] selectkbest__k=23 ...............................................
[CV] ................................ selectkbest__k=23, total=  13.1s
[CV] selectkbest__k=24 ...............................................
[CV] ................................ selectkbest__k=24, total=  13.1s
[CV] selectkbest__k=24 ...............................................
[CV] ................................ selectkbest__k=24, total=  12.9s
[CV] selectkbest__k=25 ...............................................
[CV] ................................ selectkbest__k=25, total=  14.6s
[CV] selectkbest__k=25 ...............................................
[CV] ................................ selectkbest__k=25, total=  13.6s
[CV] selectkbest__k=26 ...............................................
[CV] ................................ selectkbest__k=26, total=  13.6s
[CV] selectkbest__k=26 ...............................................
[CV] ................................ selectkbest__k=26, total=  13.9s
[CV] selectkbest__k=27 ...............................................
[CV] ................................ selectkbest__k=27, total=  14.0s
[CV] selectkbest__k=27 ...............................................
[CV] ................................ selectkbest__k=27, total=  14.3s
[CV] selectkbest__k=28 ...............................................
[CV] ................................ selectkbest__k=28, total=  13.8s
[CV] selectkbest__k=28 ...............................................
[CV] ................................ selectkbest__k=28, total=  13.8s
[CV] selectkbest__k=29 ...............................................
[CV] ................................ selectkbest__k=29, total=  15.1s
[CV] selectkbest__k=29 ...............................................
[CV] ................................ selectkbest__k=29, total=  15.1s
[CV] selectkbest__k=30 ...............................................
[CV] ................................ selectkbest__k=30, total=  14.1s
[CV] selectkbest__k=30 ...............................................
[CV] ................................ selectkbest__k=30, total=  14.4s
[CV] selectkbest__k=31 ...............................................
[CV] ................................ selectkbest__k=31, total=  14.7s
[CV] selectkbest__k=31 ...............................................
[CV] ................................ selectkbest__k=31, total=  14.5s
[CV] selectkbest__k=32 ...............................................
[CV] ................................ selectkbest__k=32, total=  12.7s
[CV] selectkbest__k=32 ...............................................
[CV] ................................ selectkbest__k=32, total=  12.7s
[CV] selectkbest__k=33 ...............................................
[CV] ................................ selectkbest__k=33, total=  14.2s
[CV] selectkbest__k=33 ...............................................

[CV] ................................ selectkbest__k=33, total=  14.3s
[CV] selectkbest__k=34 ...............................................
[CV] ................................ selectkbest__k=34, total=  14.5s
[CV] selectkbest__k=34 ...............................................
[CV] ................................ selectkbest__k=34, total=  14.9s
[CV] selectkbest__k=35 ...............................................
[CV] ................................ selectkbest__k=35, total=  15.8s
[CV] selectkbest__k=35 ...............................................
[CV] ................................ selectkbest__k=35, total=  15.1s
[CV] selectkbest__k=36 ...............................................
[CV] ................................ selectkbest__k=36, total=  14.2s
[CV] selectkbest__k=36 ...............................................
[CV] ................................ selectkbest__k=36, total=  14.1s
[CV] selectkbest__k=37 ...............................................
[CV] ................................ selectkbest__k=37, total=  15.9s
[CV] selectkbest__k=37 ...............................................
[CV] ................................ selectkbest__k=37, total=  14.6s
[CV] selectkbest__k=38 ...............................................
[CV] ................................ selectkbest__k=38, total=  15.1s
[CV] selectkbest__k=38 ...............................................
[CV] ................................ selectkbest__k=38, total=  15.0s
[CV] selectkbest__k=39 ...............................................
[CV] ................................ selectkbest__k=39, total=  15.5s
[CV] selectkbest__k=39 ...............................................
[CV] ................................ selectkbest__k=39, total=  15.6s
[CV] selectkbest__k=40 ...............................................
[CV] ................................ selectkbest__k=40, total=  14.6s
[CV] selectkbest__k=40 ...............................................
[CV] ................................ selectkbest__k=40, total=  14.8s
[CV] selectkbest__k=41 ...............................................
[CV] ................................ selectkbest__k=41, total=  16.3s
[CV] selectkbest__k=41 ...............................................
[CV] ................................ selectkbest__k=41, total=  16.2s
[CV] selectkbest__k=42 ...............................................
[CV] ................................ selectkbest__k=42, total=  15.7s
[CV] selectkbest__k=42 ...............................................
[CV] ................................ selectkbest__k=42, total=  15.7s
[CV] selectkbest__k=43 ...............................................
[CV] ................................ selectkbest__k=43, total=  15.9s
[CV] selectkbest__k=43 ...............................................
[CV] ................................ selectkbest__k=43, total=  18.8s
[CV] selectkbest__k=44 ...............................................
[CV] ................................ selectkbest__k=44, total=  15.5s
[CV] selectkbest__k=44 ...............................................
[CV] ................................ selectkbest__k=44, total=  18.1s
[CV] selectkbest__k=45 ...............................................
[CV] ................................ selectkbest__k=45, total=  15.8s
[CV] selectkbest__k=45 ...............................................
[CV] ................................ selectkbest__k=45, total=  18.1s
[CV] selectkbest__k=46 ...............................................
[CV] ................................ selectkbest__k=46, total=  16.1s
[CV] selectkbest__k=46 ...............................................
[CV] ................................ selectkbest__k=46, total=  19.4s
[CV] selectkbest__k=47 ...............................................
[CV] ................................ selectkbest__k=47, total=  17.5s
[CV] selectkbest__k=47 ...............................................
[CV] ................................ selectkbest__k=47, total=  19.7s
[CV] selectkbest__k=48 ...............................................
[CV] ................................ selectkbest__k=48, total=  16.6s
[CV] selectkbest__k=48 ...............................................
[CV] ................................ selectkbest__k=48, total=  16.5s
[CV] selectkbest__k=49 ...............................................
[CV] ................................ selectkbest__k=49, total=  18.1s
[CV] selectkbest__k=49 ...............................................
[CV] ................................ selectkbest__k=49, total=  19.0s
[CV] selectkbest__k=50 ...............................................
[CV] ................................ selectkbest__k=50, total=  17.7s
[CV] selectkbest__k=50 ...............................................
[CV] ................................ selectkbest__k=50, total=  18.3s
[CV] selectkbest__k=51 ...............................................
[CV] ................................ selectkbest__k=51, total=  20.2s
[CV] selectkbest__k=51 ...............................................
[CV] ................................ selectkbest__k=51, total=  19.4s
[CV] selectkbest__k=52 ...............................................
[CV] ................................ selectkbest__k=52, total=  18.9s
[CV] selectkbest__k=52 ...............................................
[CV] ................................ selectkbest__k=52, total=  20.6s

[Parallel(n_jobs=1)]: Done  98 out of  98 | elapsed: 21.7min finished

Validation Score:  0.6788866019813439
Best parameter: {'selectkbest__k': 41}
Best estimator: Pipeline(memory=None,
     steps=[('robustscaler', RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True)), ('selectkbest', SelectKBest(k=41, score_func=<function f_classif at 0x7f1b3119a9d8>)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False))])
----------------------------------------------------------------------------------------------------
Index(['id', 'loan_amnt', 'funded_amnt', 'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'collections_12_mths_ex_med', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'],
      dtype='object')
----------------------------------------------------------------------------------------------------
Features selected:
loan_amnt
funded_amnt
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
collections_12_mths_ex_med
tot_cur_bal
total_rev_hi_lim
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_inq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_op_rev_tl
num_rev_tl_bal_gt_0
num_sats
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bc_limit
----------------------------------------------------------------------------------------------------
Features not selected:
id
acc_now_delinq
tot_coll_amt
chargeoff_within_12_mths
delinq_amnt
num_il_tl
num_rev_accts
num_tl_120dpd_2m
num_tl_30dpd
total_bal_ex_mort
total_il_high_credit_limit
----------------------------------------------------------------------------------------------------
train_labels.shape: (1309457, 2)
submission csv shape:
cat: Model1-prediction-baseline.csv: No such file or directory
1

In [3]:
################################ 
submission_url = 'Model1-prediction-baseline1.csv'

# 0 Data Source
train_features = pd.read_csv('data/train_features.csv')
train_labels = pd.read_csv('data/train_labels.csv')
test_features = pd.read_csv('data/test_features.csv')
# sample_submission = pd.read_csv('sample_submission.csv')

# 1 Set X & y - train & test
y_train = train_labels['charged_off']
X_train = train_features
X_test  = test_features

# 2 Data Wrangle
X_train = X_train.drop(columns=list1)
X_test = X_test.drop(columns=list1)
X_train = X_train[list(X_train.select_dtypes(include=[np.number]))]
X_test = X_test[list(X_train.select_dtypes(include=[np.number]))]
for i in X_train.columns:
    X_train[i] = X_train[i].fillna(X_train[i].mean())
for i in X_test.columns:
    X_test[i] = X_test[i].fillna(X_test[i].mean())
print("X_train.shape:",X_train.shape)
print("X_test.shape:",X_test.shape)

# 3 Set X & y - train & validation from X & y train
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

# 4 Make pipeline
pipeline = make_pipeline(
    RobustScaler(),
    SelectKBest(f_classif),
    RandomForestClassifier(n_estimators=500)
)

param_grid = {
#     'selectkbest__k': range(4, len(X_train.columns)+1),
    'selectkbest__k': [41],    
    }

# 5 Fit on the train set
gs = GridSearchCV(pipeline, param_grid=param_grid, cv=2, 
                  scoring='roc_auc', 
                  iid=False,
                  verbose=2)

gs.fit(X_train, y_train)

# 6 Validation Results
validation_score = gs.best_score_
print('Validation Score: ', validation_score)
print('Best parameter:', gs.best_params_)
print('Best estimator:', gs.best_estimator_)

# 7 Print which features was selected
selector = gs.best_estimator_.named_steps['selectkbest']
all_names = X_train.columns
selected_mask = selector.get_support()
selected_names=all_names[selected_mask]
unselected_names = all_names[~selected_mask]
print("-"*100)

print(all_names)
print("-"*100)
print('Features selected:')
for name in selected_names:
  print(name)
print("-"*100)

print("Features not selected:")
for name in unselected_names:
  print(name)
print("-"*100)

# 8 Make Prediction and Save submission
y_pred=gs.predict(X_test)
# for google colab
# submission_url = '/content/drive/My Drive/Colab Notebooks/Model1-prediction.csv'
submission(y_pred,test_features,submission_url)

print("train_labels.shape:",train_labels.shape)
print("submission csv shape:")
pd.read_csv(submission_url).shape

X_train.shape: (1309457, 52)
X_test.shape: (26724, 52)
(982092, 52) (327365, 52) (982092,) (327365,)
Fitting 2 folds for each of 1 candidates, totalling 2 fits
[CV] selectkbest__k=41 ...............................................
[CV] ................................ selectkbest__k=41, total=25.7min
[CV] selectkbest__k=41 ...............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 27.9min remaining:    0.0s

[CV] ................................ selectkbest__k=41, total=25.6min

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 55.7min finished

Validation Score:  0.6893237469573033
Best parameter: {'selectkbest__k': 41}
Best estimator: Pipeline(memory=None,
     steps=[('robustscaler', RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True)), ('selectkbest', SelectKBest(k=41, score_func=<function f_classif at 0x7fe38503c7b8>)), ('randomforestclassifier', RandomForestClassifier(bootstrap=True, class_weight=None, cr...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])
----------------------------------------------------------------------------------------------------
Index(['id', 'loan_amnt', 'funded_amnt', 'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'collections_12_mths_ex_med', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit'],
      dtype='object')
----------------------------------------------------------------------------------------------------
Features selected:
loan_amnt
funded_amnt
installment
annual_inc
dti
delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
total_acc
collections_12_mths_ex_med
tot_cur_bal
total_rev_hi_lim
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_inq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_op_rev_tl
num_rev_tl_bal_gt_0
num_sats
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bc_limit
----------------------------------------------------------------------------------------------------
Features not selected:
id
acc_now_delinq
tot_coll_amt
chargeoff_within_12_mths
delinq_amnt
num_il_tl
num_rev_accts
num_tl_120dpd_2m
num_tl_30dpd
total_bal_ex_mort
total_il_high_credit_limit
----------------------------------------------------------------------------------------------------

NameError: name 'submission' is not defined

In [5]:
submission(y_pred,test_features,submission_url)

print("train_labels.shape:",train_labels.shape)
print("submission csv shape:")
pd.read_csv(submission_url).shape

train_labels.shape: (1309457, 2)
submission csv shape:

(26724, 2)